### PR TITLE
1.1

### PR DESCRIPTION
**Pull request by monicakogler**
what do u guys think about this?

- do we wanna include anything like "Source on GitHub. Built by Tyler." ?
- needs endorsement asterisk functionality please

Screen Shot 2020-09-25 at 6 27 06 PM

### CODE REVIEW

**Comment by psugihara** [comment]
def want to link to github yeah

**Comment by psugihara** [comment]
feels really nice.

some thoughts...

- "GitHub" text link could go in a footer
- the pic of bernie was compelling. fun pic of biden could be good too.
- how could you get people to share this more?

**Comment by tvler** [comment]
Instead of merging to master could we push to another branch? That way we could ship these changes and do the other stuff later

**Comment by tvler** [comment]
I think the dsa-la is endorsing nithya Raman and Fatima Iqbal-Zubair this election, their names will be below the fold but it could be cool to throw in their headshots where they appear in the guide!

**Comment by monicakogler** [comment]
cooooool cool cool ~

down to not merge to master, down for whatever... should we just keep working off this branch or ? 

wanna add back the headshot logic or shall i ?

**Comment by tvler** [comment]
eh we could just do that later down the line I think! I'll fix the merge conflicts & merge this to master! nvm what I said about not merging this to the master branch lol ❤️

**Pull request merged**
